# Generated by Django 3.2.25 on 2024-05-18 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genre_category',
            new_name='genre',
        ),
    ]
