# Generated by Django 4.2 on 2024-10-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='blurb',
            field=models.TextField(blank=True),
        ),
    ]
