# Generated by Django 4.2 on 2024-10-08 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0007_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookmark',
            field=models.ManyToManyField(blank=True, default=None, related_name='bookmark', to=settings.AUTH_USER_MODEL),
        ),
    ]
